apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketintel

resources:
  - ../../base

configMapGenerator:
  - name: marketintel-config
    behavior: merge
    literals:
      - DJANGO_ALLOWED_HOSTS=api.marketintel.example.com
      - LOG_LEVEL=INFO

patches:
  - path: prod-replicas.yaml
